### ISSUE TITLE
[Add function] 가시적인 View

### ISSUE THREAD

**Issue by Khyojung** [YukyungSeo/blackjack_realcoding#10]
화면 제일 윗쪽에 내 이름과 현재 내가 보유한 금액을 표시해줘야 한다.

**Comment by Khyojung** [comment]
제가 하겠습니다!

**Comment by Khyojung** [comment]
해결했습니다~

**Comment by sy06** [comment]
효정씨,, 새로운 user를 가입시키면 가시적인 view가 안나와요
오류 발견 ! 저는 그럼 20000 총총,, ! !

**Comment by Khyojung** [comment]
가시적인 view 나오도록 수정했습니다~!

**Comment by chojpsh1** [comment]
더블 다운 시 현재 잔액에 적용되지 않아요~

**Comment by Khyojung** [comment]
해결했습니다~
