### ISSUE TITLE
[Bug fix] 21이 넘어가면 Bust

### ISSUE THREAD

**Issue by YukyungSeo** [YukyungSeo/blackjack_realcoding#2]
21이 넘어가면 Bust
player가 21이 넘어가면 무조건 져야 해요.

**Comment by chojpsh1** [comment]
제가 합니다.

**Comment by sy06** [comment]
제가 수정할게요!

**Comment by YukyungSeo** [comment]
player가 bust되었을 때 
dealer의 sum이 player보다 숫자가 크면 player가 win하는 에러를 수정해야함

**Comment by sy06** [comment]
정말 해결했습니다!
