### ISSUE TITLE
[Bug fix] 게임끝난 후, DB 저장

### ISSUE THREAD

**Issue by YukyungSeo** [YukyungSeo/blackjack_realcoding#3]
게임이 끝났을 때,  실제 DB에 반영이 되지 않습니다.

**Comment by chojpsh1** [comment]
내가 할게여

**Comment by chojpsh1** [comment]
처리했습니다~u~

**Comment by chojpsh1** [comment]
처리가 덜 되었습니다.

**Comment by chojpsh1** [comment]
진짜진짜 완료되었습니다ㅠㅠ

**Comment by Khyojung** [comment]
게임이 끝난 후에 DB에 계좌 금액이 반영이 되지 않습니다. 수정부탁드려요

**Comment by sy06** [comment]
게임을 진행한 후,
처음 화면인 login, signup 기능이 있는 화면으로 돌아가면 게임이 끝난 직후의 account가 DB에 반영되지 않음을 수정해야함

**Comment by sy06** [comment]
게임을 진행한 후,
처음 화면인 login, signup 기능이 있는 화면으로 돌아가도 게임이 끝난 직후의 account를 DB에 반영하도록 수정하였습니다!
